# Generated by Django 5.0.3 on 2024-04-09 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0003_delete_service_remove_config_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
