# Generated by Django 5.0.3 on 2024-03-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=500)),
                ('port', models.IntegerField()),
                ('sleep', models.IntegerField(default=0, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('active', models.BooleanField(default=True, null=True)),
                ('commands', models.CharField(max_length=500)),
            ],
        ),
    ]
