# Generated by Django 5.0.3 on 2024-03-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='desc',
            field=models.CharField(blank=True, default='Sem descrição', max_length=200, null=True),
        ),
    ]
