# Generated by Django 5.0.3 on 2024-03-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_program_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='desc',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
