# Generated by Django 5.0.3 on 2024-03-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_alter_program_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='program',
            name='path',
        ),
        migrations.AddField(
            model_name='program',
            name='folder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
