# Generated by Django 5.0.3 on 2024-03-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_config_remove_program_path_program_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='env',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
