# Generated by Django 5.0.3 on 2024-03-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_program_env'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
