# Generated by Django 5.0.3 on 2024-03-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_notifciation'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifciation',
            name='checked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
