# Generated by Django 5.0.3 on 2024-03-11 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0008_notifciation_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sleep', models.IntegerField(default=0, null=True)),
                ('status', models.BooleanField(default=False, null=True)),
                ('active', models.BooleanField(default=False, null=True)),
                ('env', models.BooleanField(default=False, null=True)),
                ('commands', models.CharField(max_length=500)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
            ],
        ),
    ]
