# Generated by Django 5.0.3 on 2024-03-12 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_subprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='sleep',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_programs', to='program.program'),
        ),
    ]
