# Generated by Django 5.0.3 on 2024-03-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_alter_program_sleep_alter_subprogram_program'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notifciation',
            new_name='Notification',
        ),
    ]
