# Generated by Django 5.0.3 on 2024-03-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_rename_notifciation_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='server',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
