# Generated by Django 5.0.3 on 2024-04-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_program_server'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
    ]
