# Generated by Django 5.0.3 on 2024-04-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0013_delete_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='env',
        ),
        migrations.AddField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('server', 'Servidor'), ('service', 'Serviço')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
