# Generated by Django 5.0.3 on 2024-04-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_remove_program_env_program_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='type',
            field=models.CharField(choices=[('server', 'Servidor'), ('service', 'Serviço'), ('page', 'Pagina Estatica')], max_length=100),
        ),
    ]
