# Generated by Django 5.0.3 on 2024-04-11 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0015_alter_program_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='server',
        ),
    ]
