# Generated by Django 5.0.3 on 2024-04-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ubuntu_pass', models.CharField(max_length=200)),
                ('path_nginx', models.CharField(max_length=500)),
                ('path_programs', models.CharField(max_length=500)),
            ],
        ),
    ]
