# Generated by Django 5.0.3 on 2024-04-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='ip_server',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
