# Generated by Django 5.0.3 on 2024-04-12 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_nginxbackup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nginxbackup',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 4, 12, 14, 13, 43, 833350), null=True),
        ),
    ]
